server:
  port: 8100

spring:
  datasource:
    url: jdbc:h2:mem:inventory
  application:
    name: inventoryMS
  profiles:
    active: email, aws
  cloud:
    config:
      name: shop
  config:
    import: configserver:http://localhost:8888
  servlet:
    multipart:
      max-file-size: 8000000
