server:
  port: 8100

spring:
  datasource:
    url: jdbc:h2:mem:inventory
    driverClassName: org.h2.Driver
    password: password
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:      ddl-auto: create
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: inventoryMS
  profiles:
    active: email, aws
#  cloud:
#    config:
#      name: shop
#      enabled: true
#      uri: http://localhost:8888
#      label: main
#  config:
#    import: configserver:http://localhost:8888
  servlet:
    multipart:
      max-file-size: 8000000

hystrix:
  dashboard:
    proxy-stream-allow-list: '*'
  metrics:
    enabled: true

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
      