server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:accounts
  application:
    name: accountsMS
  profiles:
    active: email
  cloud:
    config:
      name: shop
  config:
    import: configserver:http://localhost:8888